### ISSUE TITLE
Dataset peptide_fdr does not exist for group 

### ISSUE THREAD

**Issue by treitpeter** [MannLabs/alphapept#315]
Running 311 metaproteome files against CaZy database, machine 10.31.1

error message: 

'''Dataset peptide_fdr does not exist for group / of <HDF_File D:\\Dari\\Dari_RAWs_Main\\20210513_EXPL0_PeTr_SA_T760_1285_20210528083210.ms_data.hdf>.'''

**Version 
 - OS:  Windows
 - Version 0.3.26
 - Installation Type  Python

**Comment by k-Vartika** [comment]
I get the same error (data consists of fractions, DDA mode) for Alphapept version 0.4.2. 
error: '''Dataset peptide_fdr does not exist for group / of <HDF_File E:\\QPC_Analysis\\AlphaPept\\XXX\\XXX.ms_data.hdf>.'''

```
workflow:
  continue_runs: false
  create_database: true
  import_raw_data: true
  find_features: true
  search_data: true
  recalibrate_data: true
  align: true
  match: true
  lfq_quantification: true
```
