### ISSUE TITLE
additional info on output in results.csv required

### ISSUE THREAD

**Issue by adder** [MannLabs/alphapept#386]
Hey,

I wanted to get the MS1 peak intensities of all peptide precursors in a couple of samples run on a Thermo orbitrap.
I've run the default alphapept work flow and was looking at the results in the results.csv output.

I am a bit confused on what each row in this csv file represents (a detected feature, a PSM, ...?)

Below I have added some rows of this file after filtering out 1 precursor peptide from 1 sample. (I inverted the dataframe for readability)
As you can see, I have 7 entries for this precursor peptide of which most values are duplicates between the entries.
5 entries have a "total_int" peak intensity of 76499392 and 2 entries have a peak intensity of 73658619.
The retention times between these 2 groups are overlaping.
What does this mean?
Are there 2 peaks detected by alpha pept?
What are the 5 and 2 duplicates representing?

I hope I am clear enough in my questions

Thanks

```
┌──────────────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│             variable │        81255 │        81258 │        81264 │        81267 │        81273 │        81276 │        81279 │
│               String │          Any │          Any │          Any │          Any │          Any │          Any │          Any │
├──────────────────────┼──────────────┼──────────────┼──────────────┼──────────────┼──────────────┼──────────────┼──────────────┤
│              level_0 │       124923 │       124924 │       124925 │       124926 │       124927 │       124928 │       124929 │
│      abs_delta_m_ppm │      6.51079 │     0.486064 │      6.51079 │      6.51079 │     0.486064 │      6.51079 │      6.51079 │
│           b-H2O_hits │            0 │            0 │            0 │            0 │            0 │            0 │            0 │
│           b-NH3_hits │            5 │            5 │            5 │            5 │            5 │            5 │            5 │
│               b_hits │            5 │            3 │            5 │            5 │            3 │            5 │            5 │
│               charge │          2.0 │          2.0 │          2.0 │          2.0 │          2.0 │          2.0 │          2.0 │
│               db_idx │       593774 │       593774 │       593774 │       593774 │       593774 │       593774 │       593774 │
│                decoy │        false │        false │        false │        false │        false │        false │        false │
│              delta_m │   0.00231582 │ -0.000155673 │   0.00231582 │   0.00231582 │ -0.000155673 │   0.00231582 │   0.00231582 │
│          delta_m_ppm │      6.51079 │    -0.486064 │      6.51079 │      6.51079 │    -0.486064 │      6.51079 │      6.51079 │
│                 dist │     0.137645 │     0.205767 │     0.137026 │     0.137026 │     0.205767 │     0.137645 │     0.137645 │
│          feature_idx │        37063 │        37060 │        37056 │        37057 │        37061 │        37062 │        37058 │
│         feature_rank │            1 │            1 │            1 │            1 │            1 │            1 │            1 │
│                 fwhm │     0.272817 │     0.272817 │     0.290104 │     0.290104 │     0.272817 │     0.272817 │     0.272817 │
│                 hits │      13.4572 │      11.3134 │      13.4572 │      13.4572 │      11.3134 │      13.4572 │      13.4572 │
│             int_apex │    7.93186e7 │    7.93186e7 │    8.88731e7 │    8.88731e7 │    7.93186e7 │    7.93186e7 │    7.93186e7 │
│            int_ratio │    1.41715e6 │     1.1277e6 │    1.41715e6 │    1.41715e6 │     1.1277e6 │    1.41715e6 │    1.41715e6 │
│              int_sum │    2.58312e9 │    2.58312e9 │    2.86642e9 │    2.86642e9 │    2.58312e9 │    2.58312e9 │    2.58312e9 │
│              ion_idx │      1143002 │      1143051 │      1143165 │      1143214 │      1143320 │      1143377 │      1143426 │
│              ion_int │      missing │      missing │      missing │      missing │      missing │      missing │      missing │
│            ion_types │      missing │      missing │      missing │      missing │      missing │      missing │      missing │
│                 mass │      947.482 │      947.482 │      947.482 │      947.482 │      947.482 │      947.482 │      947.482 │
│          matched_int │     42514501 │     29320096 │     42514501 │     42514501 │     29320096 │     42514501 │     42514501 │
│    matched_int_ratio │      0.55575 │     0.398054 │      0.55575 │      0.55575 │     0.398054 │      0.55575 │      0.55575 │
│ matched_ion_fraction │     0.747623 │     0.628523 │     0.747623 │     0.747623 │     0.628523 │     0.747623 │     0.747623 │
│                   mz │      474.748 │      474.748 │      474.748 │      474.748 │      474.748 │      474.748 │      474.748 │
│                 n_AA │            9 │            9 │            9 │            9 │            9 │            9 │            9 │
│           n_internal │            0 │            0 │            0 │            0 │            0 │            0 │            0 │
│               n_ions │           30 │           26 │           30 │           30 │           26 │           30 │           30 │
│             n_missed │            0 │            0 │            0 │            0 │            0 │            0 │            0 │
│       naked_sequence │    WAVATSGTR │    WAVATSGTR │    WAVATSGTR │    WAVATSGTR │    WAVATSGTR │    WAVATSGTR │    WAVATSGTR │
│          prec_offset │ -7.50333e-12 │ -7.50333e-12 │ -7.50333e-12 │ -7.50333e-12 │ -7.50333e-12 │ -7.50333e-12 │ -7.50333e-12 │
│      prec_offset_ppm │  -7.91923e-9 │  -7.91923e-9 │  -7.91923e-9 │  -7.91923e-9 │  -7.91923e-9 │  -7.91923e-9 │  -7.91923e-9 │
│     prec_offset_raw  │ -0.000166288 │ -0.000166288 │ -0.000166288 │ -0.000166288 │ -0.000166288 │ -0.000166288 │ -0.000166288 │
│ prec_offset_raw_ppm  │  -7.91923e-9 │  -7.91923e-9 │  -7.91923e-9 │  -7.91923e-9 │  -7.91923e-9 │  -7.91923e-9 │  -7.91923e-9 │
│            precursor │  WAVATSGTR_2 │  WAVATSGTR_2 │  WAVATSGTR_2 │  WAVATSGTR_2 │  WAVATSGTR_2 │  WAVATSGTR_2 │  WAVATSGTR_2 │
│            query_idx │        84840 │        84841 │        84843 │        84844 │        84846 │        84847 │        84848 │
│                 rank │            1 │            1 │            1 │            1 │            1 │            1 │            1 │
│       rank_precursor │            1 │            1 │            1 │            1 │            1 │            1 │            1 │
│              raw_idx │        22871 │        22746 │        22871 │        22871 │        22746 │        22871 │        22871 │
│             raw_rank │            1 │            1 │            1 │            1 │            1 │            1 │            1 │
│                   rt │      52.9324 │      52.9324 │       52.948 │       52.948 │      52.9324 │      52.9324 │      52.9324 │
│              rt_apex │      52.9324 │      52.9324 │       52.948 │       52.948 │      52.9324 │      52.9324 │      52.9324 │
│               rt_end │      53.3636 │      53.3636 │      53.3741 │      53.3741 │      53.3636 │      53.3636 │      53.3636 │
│             rt_start │      52.7476 │      52.7476 │      52.7395 │      52.7395 │      52.7476 │      52.7476 │      52.7476 │
│              scan_no │        34686 │        34547 │        34686 │        34686 │        34547 │        34686 │        34686 │
│                score │     0.992781 │     0.992781 │     0.992781 │     0.992781 │     0.992781 │     0.992781 │     0.992781 │
│             sequence │    WAVATSGTR │    WAVATSGTR │    WAVATSGTR │    WAVATSGTR │    WAVATSGTR │    WAVATSGTR │    WAVATSGTR │
│               target │         true │         true │         true │         true │         true │         true │         true │
│            total_int │     76499392 │     73658619 │     76499392 │     76499392 │     73658619 │     76499392 │     76499392 │
│             x_tandem │      32.9575 │      29.5901 │      32.9575 │      32.9575 │      29.5901 │      32.9575 │      32.9575 │
│           y-H2O_hits │            5 │            5 │            5 │            5 │            5 │            5 │            5 │
│           y-NH3_hits │            7 │            5 │            7 │            7 │            5 │            7 │            7 │
│               y_hits │            8 │            8 │            8 │            8 │            8 │            8 │            8 │
│             filename │           /f │           /f │           /f │           /f │           /f │           /f │           /f │
│            shortname │            f │            f │            f │            f │            f │            f │            f │
│              protein │         GPP1 │         GPP1 │         GPP1 │         GPP1 │         GPP1 │         GPP1 │         GPP1 │
│        protein_group │         GPP1 │         GPP1 │         GPP1 │         GPP1 │         GPP1 │         GPP1 │         GPP1 │
│                razor │         true │         true │         true │         true │         true │         true │         true │
│          protein_idx │         4467 │         4467 │         4467 │         4467 │         4467 │         4467 │         4467 │
│        decoy_protein │        false │        false │        false │        false │        false │        false │        false │
│  n_possible_proteins │            2 │            2 │            2 │            2 │            2 │            2 │            2 │
│  index_protein_group │        38078 │        38078 │        38078 │        38078 │        38078 │        38078 │        38078 │
│  score_protein_group │     0.994902 │     0.994902 │     0.994902 │     0.994902 │     0.994902 │     0.994902 │     0.994902 │
│ target_protein_group │         true │         true │         true │         true │         true │         true │         true │
│           target_cum │         2899 │         2899 │         2899 │         2899 │         2899 │         2899 │         2899 │
│           decoys_cum │            0 │            0 │            0 │            0 │            0 │            0 │            0 │
│                  fdr │          0.0 │          0.0 │          0.0 │          0.0 │          0.0 │          0.0 │          0.0 │
│              q_value │          0.0 │          0.0 │          0.0 │          0.0 │          0.0 │          0.0 │          0.0 │
│             fraction │            1 │            1 │            1 │            1 │            1 │            1 │            1 │
│           int_sum_dn │    2.45879e9 │    2.45879e9 │    2.72846e9 │    2.72846e9 │    2.45879e9 │    2.45879e9 │    2.45879e9 │
└──────────────────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┘
```

**Comment by straussmaximilian** [comment]
Hi,
the results.csv will give you the identified peptides. Descriptions about the columns can be found [here](https://mannlabs.github.io/alphapept/file_formats.html#Column-headers). 

> I am a bit confused on what each row in this csv file represents (a detected feature, a PSM, ...?)

Each entry corresponds to an identified MS2 spectrum and its matching MS1 feature.

> Below I have added some rows of this file after filtering out 1 precursor peptide from 1 sample. (I inverted the dataframe for readability)
? As you can see, I have 7 entries for this precursor peptide of which most values are duplicates between the entries.
5 entries have a "total_int" peak intensity of 76499392 and 2 entries have a peak intensity of 73658619.
The retention times between these 2 groups are overlaping.
What does this mean?
Are there 2 peaks detected by alpha pept?
What are the 5 and 2 duplicates representing?

The data looks quite interesting. My brief analysis:
- Each entry has a unique feature_idx, so each entry was matched to a unique feature.
- It is odd that features are detected at the same time.
- Each entry has a unique scan_no, so they all are indiviual scans. This can make sense if the feature was repeatedly detected.
- There are some duplicates for total_int - this is the intensity of all MS2 fragments and not the feature intensity - it is odd that there are duplicates
- There are also some duplicates for int_sum - which is the MS1 feautre intensity

Typically, each precursor should only be reported once, so this looks like something went wrong here. Would you mind sharing the file and the alphapept settings used?

**Comment by adder** [comment]
Hey Maximilian,

Thanks for your quick reply!

So if I am correct it looks like there are 2 different features detected for WAVATSGTR_2 in this file . So I should probably pick one or somehow combine them if I wanted to have the total WAVATSGTR_2 intensity in this sample.
What worries me a bit is that the rt times are overlapping and the intensity values are close.
I suspect it was probably the same peak (and I should probably only pick one of the two peaks),

> 
>  * There are some duplicates for total_int - this is the intensity of all MS2 fragments and not the feature intensity - it is odd that there are duplicates
> 
My bad, I wanted to look at the  ' int_sum' off course  (2.86642e9 and  2.58312e9)

>       
> Typically, each precursor should only be reported once, so this looks like something went wrong here. Would you mind sharing  the file and the alphapept settings used?

Not sure if you only want the results.csv or all files.
 results.csv is 1 gb and you download it here:
https://www.dropbox.com/s/n9tz2fobyq2bvtb/results.zip?dl=0

If you want to repeat the analysis, you can also do it since the raw files are already public on Pride.
https://www.ebi.ac.uk/pride/archive/projects/PXD028735
This is a huge experiment but I only used  a subset of the raw files (see the yaml file to see which raw files I used)

The workflow yaml file is below

Thanks

```
workflow:
  continue_runs: false
  create_database: true
  import_raw_data: true
  find_features: true
  search_data: true
  recalibrate_data: true
  align: false
  match: false
  lfq_quantification: true
general:
  n_processes: 1
experiment:
  results_path: null
  shortnames:
  - LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01
  - LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02
  - LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03
  - LFQ_Orbitrap_DDA_Condition_A_Sample_Beta_01
  - LFQ_Orbitrap_DDA_Condition_A_Sample_Beta_02
  - LFQ_Orbitrap_DDA_Condition_A_Sample_Beta_03
  - LFQ_Orbitrap_DDA_Condition_A_Sample_Gamma_01
  - LFQ_Orbitrap_DDA_Condition_A_Sample_Gamma_02
  - LFQ_Orbitrap_DDA_Condition_A_Sample_Gamma_03
  - LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01
  - LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02
  - LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03
  - LFQ_Orbitrap_DDA_Condition_B_Sample_Beta_01
  - LFQ_Orbitrap_DDA_Condition_B_Sample_Beta_02
  - LFQ_Orbitrap_DDA_Condition_B_Sample_Beta_03
  - LFQ_Orbitrap_DDA_Condition_B_Sample_Gamma_01
  - LFQ_Orbitrap_DDA_Condition_B_Sample_Gamma_02
  - LFQ_Orbitrap_DDA_Condition_B_Sample_Gamma_03
  - LFQ_Orbitrap_DDA_QC_01
  - LFQ_Orbitrap_DDA_QC_02
  - LFQ_Orbitrap_DDA_QC_03
  - LFQ_Orbitrap_DDA_QC_05
  - LFQ_Orbitrap_DDA_QC_06
  - LFQ_Orbitrap_DDA_QC_07
  - LFQ_Orbitrap_DDA_QC_09
  - LFQ_Orbitrap_DDA_QC_10
  - LFQ_Orbitrap_DDA_QC_11
  file_paths:
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_A_Sample_Beta_01.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_A_Sample_Beta_02.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_A_Sample_Beta_03.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_A_Sample_Gamma_01.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_A_Sample_Gamma_02.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_A_Sample_Gamma_03.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_B_Sample_Beta_01.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_B_Sample_Beta_02.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_B_Sample_Beta_03.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_B_Sample_Gamma_01.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_B_Sample_Gamma_02.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_Condition_B_Sample_Gamma_03.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_QC_01.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_QC_02.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_QC_03.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_QC_05.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_QC_06.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_QC_07.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_QC_09.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_QC_10.raw
  - /home/st/Documents/lfq_benchmark/benchmark_analysis/input_data_all/LFQ_Orbitrap_DDA_QC_11.raw
  fractions:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - '15'
  - '16'
  - '17'
  - '18'
  - '19'
  - '20'
  - '21'
  - '22'
  - '23'
  - '24'
  - '25'
  - '26'
  - '27'
  matching_groups: []
  database_path: null
  fasta_paths:
  - /home/st/.alphapept/fasta/2021_12_29_Saccharomyces_cerevisiae_UP000002311.fasta
  - /home/st/.alphapept/fasta/2021_12_29_Homo_sapiens_UP000005640.fasta
  - /home/st/.alphapept/fasta/2021_12_29_Escherichia_coli_UP000000625.fasta
  fraction_dict:
    '1':
    - LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_01.raw
    '10':
    - LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_01.raw
    '11':
    - LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_02.raw
    '12':
    - LFQ_Orbitrap_DDA_Condition_B_Sample_Alpha_03.raw
    '13':
    - LFQ_Orbitrap_DDA_Condition_B_Sample_Beta_01.raw
    '14':
    - LFQ_Orbitrap_DDA_Condition_B_Sample_Beta_02.raw
    '15':
    - LFQ_Orbitrap_DDA_Condition_B_Sample_Beta_03.raw
    '16':
    - LFQ_Orbitrap_DDA_Condition_B_Sample_Gamma_01.raw
    '17':
    - LFQ_Orbitrap_DDA_Condition_B_Sample_Gamma_02.raw
    '18':
    - LFQ_Orbitrap_DDA_Condition_B_Sample_Gamma_03.raw
    '19':
    - LFQ_Orbitrap_DDA_QC_01.raw
    '2':
    - LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_02.raw
    '20':
    - LFQ_Orbitrap_DDA_QC_02.raw
    '21':
    - LFQ_Orbitrap_DDA_QC_03.raw
    '22':
    - LFQ_Orbitrap_DDA_QC_05.raw
    '23':
    - LFQ_Orbitrap_DDA_QC_06.raw
    '24':
    - LFQ_Orbitrap_DDA_QC_07.raw
    '25':
    - LFQ_Orbitrap_DDA_QC_09.raw
    '26':
    - LFQ_Orbitrap_DDA_QC_10.raw
    '27':
    - LFQ_Orbitrap_DDA_QC_11.raw
    '3':
    - LFQ_Orbitrap_DDA_Condition_A_Sample_Alpha_03.raw
    '4':
    - LFQ_Orbitrap_DDA_Condition_A_Sample_Beta_01.raw
    '5':
    - LFQ_Orbitrap_DDA_Condition_A_Sample_Beta_02.raw
    '6':
    - LFQ_Orbitrap_DDA_Condition_A_Sample_Beta_03.raw
    '7':
    - LFQ_Orbitrap_DDA_Condition_A_Sample_Gamma_01.raw
    '8':
    - LFQ_Orbitrap_DDA_Condition_A_Sample_Gamma_02.raw
    '9':
    - LFQ_Orbitrap_DDA_Condition_A_Sample_Gamma_03.raw
raw:
  n_most_abundant: 400
  use_profile_ms1: false
fasta:
  mods_fixed:
  - cC
  mods_fixed_terminal: []
  mods_variable:
  - oxM
  mods_variable_terminal: []
  mods_fixed_terminal_prot: []
  mods_variable_terminal_prot:
  - a<^
  n_missed_cleavages: 2
  pep_length_min: 7
  pep_length_max: 27
  isoforms_max: 1024
  n_modifications_max: 3
  pseudo_reverse: true
  AL_swap: false
  KR_swap: false
  protease: trypsin
  spectra_block: 100000
  fasta_block: 1000
  save_db: true
  fasta_size_max: 100
features:
  max_gap: 2
  centroid_tol: 8
  hill_length_min: 3
  hill_split_level: 1.3
  iso_split_level: 1.3
  hill_smoothing: 1
  hill_check_large: 40
  iso_charge_min: 1
  iso_charge_max: 6
  iso_n_seeds: 100
  hill_nboot_max: 300
  hill_nboot: 150
  iso_mass_range: 5
  iso_corr_min: 0.6
  map_mz_range: 1.5
  map_rt_range: 0.5
  map_mob_range: 0.3
  map_n_neighbors: 5
  search_unidentified: false
search:
  prec_tol: 30
  frag_tol: 30
  min_frag_hits: 7
  ppm: true
  calibrate: true
  calibration_std_prec: 5
  calibration_std_frag: 5
  parallel: true
  peptide_fdr: 0.01
  protein_fdr: 0.01
  recalibration_min: 100
score:
  method: random_forest
calibration:
  outlier_std: 3
  calib_n_neighbors: 100
  calib_mz_range: 20
  calib_rt_range: 0.5
  calib_mob_range: 0.3
matching:
  match_p_min: 0.05
  match_d_min: 3
isobaric_label:
  label: None
  reporter_frag_tolerance: 15
  reporter_frag_tolerance_ppm: true
quantification:
  max_lfq: true
  lfq_ratio_min: 1
  mode: int_sum

```
